language: node_js
node_js:
- '4.1'
cache:
  directories:
  - node_modules
  - lib
after_success:
- cat ./coverage/lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: heroku
  api_key:
    secure: ZmskeEMSXo+bX9JiPKV05O/V22iuErAR0QPe4JfnXrk96qqkWhVQmkWDLDe1gsc4zgoS9cwKeTfcmDdUrcSSBeBzOqs0mYNeGGbeJQSDvXZ7AJ44he5eRUKybVTSdKe0/7r6rZfu8kCT277qAv0xOHsYfetBXzz/2JvKdrdHnQLtHQKA4B0exlg3B5lu6utntgNUX71rhL20Ibq1ezLziM/T/nMIjGZjZbP+/ecizHNDGKRLKo19aRcLElGs2kiC7NyiPJvHUJP5kQciL8i91+smeVjTCKXnie+CDWSmqMdTsK2X5tOQh5tyKx2QGNIwlYllldQ5glBbzEaP7/3jmURZflEiyKqIBemjWgQEIaVR5Z7V7Y36los/oJli+YI+XH7an1O8HIb2T5KqNTlLQjW/7RMq45nzn4KLYGfiOzHZEow4HdQsryXSWRlzZN5UmtOGo/eLAaNv0Ec4+MAeUtvyzn7o01dfGa+cdBi9telJJ9PjFX+IvkK1CDsYikkI7GdrEgDZ2EvoSGahzmhTipaxArlsfgQd2DEfaFA5x7l1SR47XUAkwE099kxwpb0FkbMNmYBCFRi7FgQlXi3r1/6OSKCF6O0sbDLHk/MUVLlRT37PGP3+ElnfpCNWHbmDEMS7KXvY1SWYS29uw4HT2LoGQ/QlaETCtCzEnq+Il4A=
  app: quizdeck
  on:
    branch: master
    repo: bcroden/QuizDeck-Client
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/e420c4632b5411024ce1
    on_success: always
    on_failure: always
    on_start: never
