language: node_js
node_js:
- '4.1'
cache:
  directories:
    - node_modules
    - lib
after_success:
- cat ./coverage/lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: heroku
  api_key:
    secure: TVI3rFAtLSc4F/xw8blEi7LywQvpsEb/Hr4OprJ9lndka4YNwVih4YMwz7xv7Pohht5OV7XMNxLEB3NqdxiUNlEfIc077OqtqBmJ7b5uAGjVv8E2i6HpCB9Yy2qjy6qegC3JLVEoEb/qsubQsOnPL8hSSSn4F2KH8SHoeAlIVXTWJSgrx6j/PK1GJrNi8uL5/Q93sbfkcGlBjB222qHxXRyXSdnbyN5kdZUQmGGhwhIB5p4I5Y04wDkrmpE/kNtvUMYYYkJNbH/XgFnvDVnaB6w07ncYEch06/+JLDtiyU1t9OGyBMrtFJrxk7nL9s/pbFcpr56HElV4NaPTRIxiRRtitGOcpKncOqzncMJ4MEGynRaRw/fxoOnzWefYUnlm5D9/RCMMyahn/TC1niqZAb+9OmJ2Ng9s2+4W9bTW2zT/mmfzRi4OU5IndUSU5RqGgO+a7NIR/pQaui5oBkQC1137L/Ztm/m7D+V4iCi3cXtkYoC67rIRekJGCFIk+ObtS0S6vpEpvTuj/rio7TMKKpX54MOo5Qf6bzHzbX8Szgl++GZCpcyid93puMcDY6egmm3H5NTP9BWz3D7Lw41FGCfevtXeDvdSLG4DR/VH3E6/hd9FPdaSG1Qndw3e/UEJrJ+4ginABzqsE1VaF2jud85gxoFqde187es7iLLeKzg=
  app: quizdeck
  on:
    branch: master
    repo: bcroden/QuizDeck-Client
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e420c4632b5411024ce1
    on_success: always
    on_failure: always
    on_start: never
env:
  global:
    - secure: OYh8/CkUm9JJaGsTtNV3dfMT7g4vksypce366fRHdNRUlIDgXsW0aayNuEhIaKpNZcedf8/ycNbdJ9eeU97B3JcNgo8ZCqWp9tsNmvJLGUlhYefrvFLLmvcudeLm4EztGNJEqYd3Hh0fmByL1bX1oduq5RPk7/WjMGK+sDl0/Dn2lzMO10jfuIdU0VCCxf7ZMcmJMInFPSS0YvzyGRwwo3PkIRgZyinQeGrjdO/KWiWhjMl+ClVkU5oeBDqL0sdEivIi3wOSPMtv5qK7NwlssjRB62XpBDEc60jA34vZT542V3j3VGRyKRDhTFhP43nSDjSxKd7OjIGLLU11kng1zYbfmE37agk5t4AfrAZTiGYDjR5jIMiGJCQLjMWhN0ZoFCP+B/YWculRdFVDbc1/a5FovG+fiJnW77PEfNeGhRm+0L7wWumdsx1J1S6CTqm4yUxALnweFtYVWKLZxsI/RlmFqflCJOde1DeHRIWvjN7Dz/kFx5bL003A4MwjOsGHSz0trfTzR2SKaG3dRzJYUhtAuAePAhIFrMHxXl90QBhHsqfdslTJdSDpE11vVoOvjNfZjXnF0BoGrd24/irw2lH49x5XUULKPH/qDyUDsphFEFRWVIye1CMG2GIaFBMYi2wIjuGbS8oqBPidtSKjPO4sAycto1QuI8rUDuyrUR8=
    - COVERALLS_SERVICE_NAME=travis-ci
